### ISSUE TITLE
Wrong html format for type parameter in Codelabs

### ISSUE THREAD

**Issue by phamducminh** [googlecodelabs/android-datastore#10]
Hi Florina,

All generic type with icon < and > were replaced with &lt and &gt; in the Codelabs link. Please take a look.

Thanks,
MinhPham

**Comment by florina-muntenescu** [comment]
Thanks for reporting. This should have been fixed meanwhile. 
Let me know if you see this again.

**Comment by phamducminh** [comment]
My pleasure.
