### ISSUE TITLE
Does this integrate with PreferenceScreen / PreferenceFragment?

### ISSUE THREAD

**Issue by digitalheir** [googlecodelabs/android-datastore#13]
`PreferenceFragment` has a very convenient `setPreferencesFromResource` method which allows us to define settings screens as XML. Will there be something similar for this library?

**Comment by digitalheir** [comment]
I suppose we could use `android:persistent="false"` for the preference definition and then handle setting the value manually with a `ViewModel` containing the preferences data store?

**Comment by florina-muntenescu** [comment]
This is not an issue related to the codelab. Closing
