### ISSUE TITLE
DataStore 不执行 completion

### ISSUE THREAD

**Issue by JiangHaiYang01** [googlecodelabs/android-datastore#18]
runBlocking {
                createDataStore("user").data
                    .onCompletion { println("complete") }
                    .collect { println("$it") }
 }

上面这个代码执行 会一直卡着，函数挂起，未能执行 completion.   使用的是 1.0.0-alpha05 版本

**Comment by florina-muntenescu** [comment]
`datastore.data` is a `Flow` that shouldn't complete. It should emit every time there's a change in data store.

**Comment by JiangHaiYang01** [comment]
> `datastore.data`是`Flow`不应该完成的。每当数据存储发生变化时，它就会发出。

OK 明白了 THS
