### ISSUE TITLE
Wrong report link

### ISSUE THREAD

**Issue by shakalaca** [googlecodelabs/android-datastore#2]
When I click the link of "Report a mistake" in [codelab](https://codelabs.developers.google.com/codelabs/android-preferences-datastore/index.html) it doesn't bring me here, but a 404 page.

**Comment by florina-muntenescu** [comment]
Link fixed but codelab no longer valid. Check out [Proto DataStore](https://codelabs.developers.google.com/codelabs/android-proto-datastore/#0) and [Preference DataStore](https://codelabs.developers.google.com/codelabs/android-preferences-datastore/#0)
