### ISSUE TITLE
Adjust DataStore param in UserPreferencesRepository

### ISSUE THREAD

**Issue by diegocarloslima** [googlecodelabs/android-datastore#28]
On the Working with Preferences DataStore codelab section **6. Persisting data in Preferences DataStore**, there is the following snippet of code:

```kotlin
class UserPreferencesRepository(
    private val userPreferencesStore: DataStore<UserPreferences>,
    context: Context
) { ... }
```

I guess the generics type should be `Preferences` and not `UserPreferences`. Otherwise, it gives a type mismatch error when trying to instantiate the `UserPreferencesRepository`

**Comment by yalematta** [comment]
And to add on that: 
For the rest of the code in `UserPreferencesRepository`, the code snippets contain `dataStore` instead of `userPreferencesStore` as a variable name. This can be a little confusing.

**Comment by heskadon** [comment]
Yes should be like : 

`class UserPreferencesRepository(
    private val userPreferencesStore: DataStore<Preferences>,
    context: Context
) { ... }`

**Comment by mmoczkowski** [comment]
Thank you, fix is underway. Issue can be tracked in #45
