### ISSUE TITLE
Could not find androidx.datastore:datastore-preferences:1.0.0-alpha01

### ISSUE THREAD

**Issue by TheMaxCoder** [googlecodelabs/android-datastore#3]
I am trying out the codelab but unable to resolve the dependency for datastore. I have tried the "preferences_datastore" branch too but the result is the same.
I could not find any information about datastore's Gradle dependency on [Jetpack Explorer](https://developer.android.com/jetpack/androidx/explorer?case=all) and [AndroidX releases Page](https://developer.android.com/jetpack/androidx/versions).

Kindly look into this. Thanks

**Comment by Arogyathegreat** [comment]
I did find the datastore library in their [codebase](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:datastore/). 
Could possibly be an error in version number.

**Comment by khpproud** [comment]
It is currently not registered on google's maven repository(https://maven.google.com/web/index.html). So just wait till to be update.

**Comment by florina-muntenescu** [comment]
Library was published. Try it out!
