### ISSUE TITLE
[Codelab] Data type & variable names don't match in codelab

### ISSUE THREAD

**Issue by anidhamal** [googlecodelabs/android-datastore#30]
In codelab's [Chapter 6: Persisting data in Preferences DataStore](https://developer.android.com/codelabs/android-preferences-datastore#5)
```
class UserPreferencesRepository(
    private val userPreferencesStore: DataStore<UserPreferences>,
    ...
) { ... }
```

1. There is no way to pass DataStore<**UserPreferences**> through delegate. This needs to be updated to DataStore<**Preferences**>
2. It doesn't mention where `updateShowCompleted` & `userPreferencesFlow` should be added. These method/variable make use of `dataStore` so feels like they belong in `TasksActivity`. maybe it's confusing because variable name used in `UserPreferencesRepository` as `userPreferencesStore`.

**Comment by mmoczkowski** [comment]
Thanks, the function signature has been updated
