### ISSUE TITLE
[UI] RecyclerView Bottom Padding

### ISSUE THREAD

**Issue by forceporquillo** [googlecodelabs/android-datastore#33]
This may be out of topic in the datastore sample implementation itself. But, the recyclerView part is a bit odd-looking even if the list items are already collapsed, the padding still exists.

![image](https://user-images.githubusercontent.com/51302519/125327073-4e57fc80-e375-11eb-87d1-a1d7137afe24.png)

On the other hand, when the list isn't fully collapsed. The padding still exists.

![image](https://user-images.githubusercontent.com/51302519/125326547-c07c1180-e374-11eb-945f-bc3bdd82d8bb.png)

This might be a minor issue in the UI part to fix this.
```
android:clipToPadding="false"
````

**Comment by mmoczkowski** [comment]
Fix has been merged. Thanks again!
