### ISSUE TITLE
How to test dataStore?

### ISSUE THREAD

**Issue by simplekjl** [googlecodelabs/android-datastore#35]
is there a way or example of how to test it?

**Comment by mmoczkowski** [comment]
@simplekjl Check out this article by Simona Stojanovic @simona-anomis 

https://medium.com/androiddevelopers/datastore-and-testing-edf7ae8df3d8

**Comment by ammargitham** [comment]
@simona-anomis `TestCoroutineDispatcher` and `TestCoroutineScope` used in the article are now deprecated. Needs to be updated.
