### ISSUE TITLE
The page is not found.

### ISSUE THREAD

**Issue by bestofbest1** [googlecodelabs/android-datastore#42]
https://developer.android.com/codelabs/android-preferences-datastore#0

has below link in the document. But, the page is not found.

-> https://codelabs.developers.google.com/codelabs/advanced-kotlin-coroutines 
-> 404 Error

**Comment by mmoczkowski** [comment]
Fix is underway

**Comment by mmoczkowski** [comment]
Thank for reporting, the link has been changed to https://developer.android.com/codelabs/advanced-kotlin-coroutines
