### ISSUE TITLE
Incorrect parameter in the constructor of the UserPreferencesRepository 

### ISSUE THREAD

**Issue by Arunm619** [googlecodelabs/android-datastore#45]
On [Page 6](https://developer.android.com/codelabs/android-preferences-datastore#5) of the lab, 

the third code snippet shows 
``` class UserPreferencesRepository(private val dataStore: DataStore<UserPreferences>)  ``` which is incorrect.

The right one is 

```class UserPreferencesRepository(private val dataStore: DataStore<Preferences>) ```

**Comment by mmoczkowski** [comment]
Thank you. Fix will be issued soon.

**Comment by mmoczkowski** [comment]
Duplicate of #30

**Comment by mmoczkowski** [comment]
Thank you, this has been fixed
