### ISSUE TITLE
DataStore<Preferences>

### ISSUE THREAD

**Issue by nynganini** [googlecodelabs/android-datastore#56]
When creating UserPreferencesRepository the type should be DataStore\<Preferences\> instead of DataStore\<UserPreferences\>

**Comment by coodin** [comment]
I have encounter the same problem so I decided to look the finished repository to check how they have done that and they have also written DataStore<Preferences> inside UserPreferencesRepository which is same with your answer.

**Comment by ccornici** [comment]
Looks like they just write code in notepad and commit it, and never correct it either.

**Comment by donnfelker** [comment]
These kind of mistakes can (and do) throw beginners off the wagon really easily. This should be fixed ASAP. 

Offending page: https://developer.android.com/codelabs/android-preferences-datastore#5

**Comment by mmoczkowski** [comment]
Thanks, I agree this needs to be fixed asap. Working on it.

**Comment by mmoczkowski** [comment]
Closing as a duplicate of #45
